import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
    variable: "--font-geist-sans",
    weight: ["200", "300", "500", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "AMI Especialidades & Ensino | Odontologia Especializada",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body
                cz-shortcut-listen="true"
                className={`${poppins.className} antialiased scroll-smooth`}
            >
                <main className="overflow-x-hidden">{children}</main>
            </body>
        </html>
    );
}
